- name: Clone repository
  git:
    repo: 'https://github.com/loan-petit/lifetools.git'
    dest: ~/lifetools/
    force: yes
    version: master

- name: Pull changes in repository
  shell: git pull
  args:
    chdir: ~/lifetools/

- name: Tear down existing services
  docker_compose:
    project_src: lifetools
    files: docker-compose.pre-prod.yml
    state: absent

- name: Prune docker system to avoid taking too much space
  docker_prune:
    containers: yes
    images: yes
    networks: yes
    builder_cache: yes

- name: Create and start services
  docker_compose:
    project_src: lifetools
    files: docker-compose.pre-prod.yml
  register: output

- name: Run `docker-compose up` again
  docker_compose:
    project_src: lifetools
    files: docker-compose.pre-prod.yml
    build: no
  register: output

- name: Assert that the output doesn't differ between the execution of the two 'up' tasks
  assert:
    that: "not output.changed "

- name: Stop all services
  docker_compose:
    project_src: lifetools
    files: docker-compose.pre-prod.yml
    build: no
    stopped: yes
  register: output

- name: Assert that services aren't running.
  assert:
    that:
      - "not nginx.lifetools_nginx.state.running"
      - "not prisma.lifetools_prisma.state.running"
      - "not postgres.lifetools_postgres.state.running"
      - "not flutter.lifetools_flutter.state.running"

- name: Restart services
  docker_compose:
    project_src: lifetools
    files: docker-compose.pre-prod.yml
    build: no
    restarted: yes
  register: output

- name: Assert that services are running.
  assert:
    that:
      - "nginx.lifetools_nginx.state.running"
      - "prisma.lifetools_prisma.state.running"
      - "postgres.lifetools_postgres.state.running"
      - "flutter.lifetools_flutter.state.running"
