- name: Install Docker and some required dependencies
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - docker
    - python-pip
    - gcc

- name: Ensure Docker daemon is running
  service:
    name: docker
    state: started

- name: Install Docker Module for Python
  pip:
    name:
      - docker
      - docker-compose
    state: latest

- name: Start (or restart) services
  docker_compose:
    project_src: ./lifetools
    files: docker-compose.prod.yml
    pull: yes

- name: Assert that services are running
  assert:
    that:
      - "nginx.lifetools_nginx.state.running"
      - "prisma.lifetools_prisma.state.running"
      - "postgres.lifetools_postgres.state.running"
      - "flutter.lifetools_flutter.state.running"
