- name: Setup Node.js
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
    . ~/.nvm/nvm.sh
    nvm install node
  args:
    creates: "~/.nvm/nvm.sh"

- name: Store Node.js version in variable
  shell: |
    . ~/.nvm/nvm.sh
    nvm version
  register: node_version

- name: Install Prisma2 CLI to use Lift
  npm:
    executable: ~/.nvm/versions/node/{{ node_version.stdout }}/bin/npm
    name: prisma2
    global: yes

- name: Apply migrations to the database using Lift from Prisma Framework
  shell: prisma2 lift up
  args:
    chdir: ./lifetools/prisma