# docker-compose.yml
version: '3'

services:
  nginx:
    image: petitloan/lifetools:nginx
    container_name: lifetools_nginx
    restart: always
    depends_on:
      - prisma
      - flutter
    ports:
      - "80:80"
      - "8081:8081"

  prisma:
    image: petitloan/lifetools:prisma
    container_name: lifetools_prisma
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./prisma/docker-compose.env
    cap_add:
      - SYS_ADMIN
    expose:
      - "4000"

  postgres:
    image: postgres:12-alpine
    container_name: lifetools_postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: lifetools
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"

  flutter:
    image: petitloan/lifetools:flutter
    container_name: lifetools_flutter
    restart: always
    expose:
      - "80"

volumes:
  db-data:
