- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install git
  yum:
    name: git

- name: Recursively remove repository directory
  file:
    path: ./lifetools
    state: absent

- name: Clone repository
  git:
    repo: 'https://github.com/loan-petit/lifetools.git'
    dest: ./lifetools
    force: yes