name: LifeTools
description: An app built using Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.3+4
  validators: ^2.0.0+1

  http: ^0.12.0+2
  rxdart: ^0.18.1

dev_dependencies:
  pedantic: ^1.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/OpenSans/OpenSans-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
