- name: Setup Node.js
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
    . ~/.nvm/nvm.sh
    nvm install node

- name: Store Node.js version in variable
  shell: |
    . ~/.nvm/nvm.sh
    nvm version
  register: node_version

- name: Install Prisma2 CLI
  npm:
    executable: ~/.nvm/versions/node/{{ node_version.stdout }}/bin/npm
    name: prisma2
    global: yes

- name: Apply migrations to the database using Prisma2
  shell: (export $(grep '^POSTGRES_URL' .env | xargs) && prisma2 migrate up --experimental)
  args:
    chdir: ./lifetools/prisma
