name: Deploy the application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build images
        run: |
          docker build -t petitloan/lifetools:nginx --build-arg APP_ENV=dev ./nginx/
          docker build -t petitloan/lifetools:prisma ./prisma/
          docker build -t petitloan/lifetools:flutter --build-arg FLUTTER_VERSION=v1.14.0 ./flutter/

      - name: Login to Docker Hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images to Docker Hub repository
        run: |
          docker push petitloan/lifetools:nginx
          docker push petitloan/lifetools:prisma
          docker push petitloan/lifetools:flutter

      - name: Load AWS EC2 private key.
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > ~/.aws_ec2_key.pem
          chmod 600 ~/.aws_ec2_key.pem

      - name: Deploy using Ansible playbook
        run: ansible-playbook playbook.yml -i production --key-file=~/.aws_ec2_key.pem
        working-directory: ./deploy/
