name: Prisma2 GraphQL API CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install npm packages and run production build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
        working-directory: ./prisma/
